/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package find.prime.numbers;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.Arrays;

class AppTest {
    @Test void solution() {
        App classUnderTest = new App();
        String[] participants = {"leo", "kiki", "eden"};
        String[] completion = {"eden", "kiki"};

        assertEquals("leo", classUnderTest.solution(participants, completion));

        String[] participants2 = {"marina", "josipa", "nikola", "vinko", "filipa"};
        String[] completion2 = {"josipa", "filipa", "marina", "nikola"};

        assertEquals("vinko", classUnderTest.solution(participants2, completion2));

        String[] participants3 = {"mislav", "stanko", "mislav", "ana"};
        String[] completion3 = {"stanko", "ana", "mislav"};

        assertEquals("mislav", classUnderTest.solution(participants3, completion3));
    }
}
