/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package find.prime.numbers;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.Arrays;

class AppTest {
    @Test void solution() {
        App classUnderTest = new App();

        int[] prices3 = {10, 7, 5, 6};
        assertEquals(
            "[1, 1, 1, 0]", 
            Arrays.toString(classUnderTest.solution(prices3))
        );

        int[] prices = {1, 2, 3, 2, 3};
        assertEquals("[4, 3, 1, 1, 0]", Arrays.toString(classUnderTest.solution(prices)));

        int[] prices2 = {1, 2, 3, 2, 3, 1, 5, 7, 9, 10, 7, 5, 6};
        assertEquals(
            "[12, 4, 1, 2, 1, 7, 6, 4, 2, 1, 1, 1, 0]", 
            Arrays.toString(classUnderTest.solution(prices2))
        );
    }
}
