/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package find.prime.numbers;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.Arrays;

class AppTest {
    @Test void solution() {
        App classUnderTest = new App();

        int[] numbers = {2, 1, 3, 4, 1};
        String acutal = Arrays.toString(classUnderTest.solution(numbers));

        assertEquals("[2, 3, 4, 5, 6, 7]", acutal);

        int[] numbers2 = {5, 0, 2, 7};
        String actual2 = Arrays.toString(classUnderTest.solution(numbers2));

        assertEquals("[2, 5, 7, 9, 12]", actual2);
    }
}
