/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package find.prime.numbers;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void makeArrayListTest() {
        App classUnderTest = new App();
        assertEquals(2, classUnderTest.makeArrayList(5).size());
        assertEquals(4, classUnderTest.makeArrayList(10).size());
    }

    @Test void solution() {
        App classUnderTest = new App();
        assertEquals(1, classUnderTest.solution(2));
        assertEquals(2, classUnderTest.solution(3));
        assertEquals(2, classUnderTest.solution(4));
        assertEquals(3, classUnderTest.solution(5));
        assertEquals(4, classUnderTest.solution(10));
    }
}
