/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package find.prime.numbers;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.Arrays;

class AppTest {
    @Test void solution() {
        App classUnderTest = new App();

        int[] inputArray = {1, 1, 3, 3, 0, 1, 1};
        String expected = Arrays.toString(classUnderTest.solution(inputArray));
        assertEquals("[1, 3, 0, 1]", expected);

        int[] inputArray2 = {4, 4, 4, 3, 3};
        String expected2 = Arrays.toString(classUnderTest.solution(inputArray2));
        assertEquals("[4, 3]", expected2);
    }
}
